-- Run this in your PostgreSQL database to create the table
CREATE TABLE IF NOT EXISTS shipments (
    id SERIAL PRIMARY KEY,
    no INTEGER,
    cargo_type VARCHAR(50),
    consignee VARCHAR(255),
    project_name VARCHAR(255) NOT NULL,
    product VARCHAR(255),
    quantity_mt NUMERIC,
    bl_number VARCHAR(255),
    shipping_line VARCHAR(255),
    vessel_name VARCHAR(255),
    voyage_number VARCHAR(255),
    pol VARCHAR(255),
    pod VARCHAR(255),
    shipment_route VARCHAR(50),
    etd DATE,
    eta DATE,
    shipment_type VARCHAR(50),
    est_sailing_days NUMERIC,
    actual_sailing_days NUMERIC,
    pib_billing DATE,
    bpn DATE,
    spjm DATE,
    behandle DATE,
    sppb DATE,
    clearance_days NUMERIC,
    start_unloading DATE,
    finish_unloading DATE,
    unloading_days NUMERIC,
    cargo_status VARCHAR(50),
    start_delivery DATE,
    enter_warehouse DATE,
    delivery_days NUMERIC,
    vendor_trucking VARCHAR(255),
    warehouse_location VARCHAR(255),
    status VARCHAR(50),
    remarks TEXT,
    year INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster upsert matching
CREATE UNIQUE INDEX idx_shipment_unique ON shipments(project_name, cargo_type, COALESCE(bl_number, ''));